title: Pratt Singh
description: Hi! This webpage shows some of
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

  - README.md


theme: jekyll-theme-cayman
